### ISSUE TITLE
Next steps for this repo

### ISSUE THREAD

**Issue by MrShutCo** [surrealdb/surrealdb.go#4] opened 2022-09-16 15:28 UTC
Hi, 
I am interested in helping develop this library, but there doesn't seem to be much info about it or what the next steps are. Is there somewhere I can be pointed to for things to do, or should I just start writing code and putting up PR requests?

**Comment by cruzanstx** [comment] 2022-09-18 06:28
I'm seconding this Issue. I also would like to contribute but not sure what the direction this is taking. I'd like to see some more documentation on how its intended to be utilized. Also is the intention to create a go library that wraps the restful/ws interactions with surrealdb? I'm more than likely going to look at the more "mature" surrealdb drivers for other languages for guidance, but it would be nice to see goals and maybe some more documentation is to how this driver is intended to be use.

**Comment by tpotjj** [comment] 2022-10-04 06:33
I would really like to start contributing, so it would be great if there is some guidance/documentation :)

**Comment by PaulLockett** [comment] 2022-10-24 01:31
I am also Interested in helping out. I just tried it, and it just seems to stall on a lot of requests.

**Comment by timpratim** [comment] 2023-10-19 09:08
Closing as the issue is not relevant anymore.

**Closed by timpratim** 2023-10-19 09:08 UTC
